spreadsheet: "https://docs.google.com/spreadsheets/d/1TcxzSeq5qWPkDVFQ5tZStXFY8ehOCnD-yqhuQrQvRcw/edit?gid=0"
spreadsheet_scratch: "https://docs.google.com/spreadsheets/d/1KaDWsUcnYQdiCQ5qFqXOjSTpuEupEN1rhV-8agFxptk/edit?gid=0"
spreadsheet_test: "https://docs.google.com/spreadsheets/d/1b6XSg-6a0X5NxH6GFTH3evEdwuZbUNYjjOfZ5akvKLA/edit?gid=0"

global_all_pcodes: "https://data.humdata.org/dataset/cb963915-d7d1-4ffa-90dc-31277e24406f/resource/793e66fe-4cdb-4076-b037-fb8c053239e2/download/global_pcodes.csv"



dataset:
  name: "hdx-hapi-operational-presence"
  title: "HDX HAPI - Coordination & Context: Operational Presence"
  tags:
    - "hxl"
    - "operational presence"
    - "who is doing what and where-3w-4w-5w"
  resource:
    name: "Global Coordination & Context: Operational Presence"
    description: "Operational Presence data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/coordination_and_context/#operational-presence) for more information"
    filename: "hdx_hapi_operational_presence_global.csv"
    headers:
      - "location_code"
      - "has_hrp"
      - "in_gho"
      - "provider_admin1_name"
      - "provider_admin2_name"
      - "admin1_code"
      - "admin1_name"
      - "admin2_code"
      - "admin2_name"
      - "admin_level"
      - "org_acronym"
      - "org_name"
      - "org_type_description"
      - "sector_code"
      - "sector_name"
      - "reference_period_start"
      - "reference_period_end"
      - "dataset_hdx_id"
      - "resource_hdx_id"
      - "warning"
      - "error"

org_dataset:
  name: "hdx-hapi-organisations"
  title: "HDX HAPI - Coordination & Context: Organisations"
  tags:
    - "hxl"
    - "operational partners"
  resource:
    name: "Global Coordination & Context: Organisations"
    description: "Organisation data from HDX HAPI"
    filename: "hdx_hapi_organisations_global.csv"
    headers:
      - "acronym"
      - "name"
      - "org_type_code"
      - "org_type_description"

dataseries_ignore:
  - "Fields Data - Operational Presence"

tags_ignore:
  - "climate hazards"
  - "climate-weather"
  - "complex emergency-conflict-security"
  - "conflict-violence"
  - "cyclones-hurricanes-typhoons"
  - "disease"
  - "drought"
  - "earthquake-tsunami"
  - "epidemics-outbreaks"
  - "flooding-storm surge"
  - "hazards and risk"
  - "natural disasters"

words_ignore:
  - "testing"
  - "district"
  - "province"
  - "region"
  - "northeast"

allowed_formats:
  - "csv"
  - "ods"
  - "tsv"
  - "xls"
  - "xlsx"

org:
  url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSfBWvSu3fKA743VvHtgf-pIGkYH7zhy-NP7DZgEV9_a6YU7vtCeWhbLM56aUL1iIfrfv5UBvvjVt7B/pub?gid=1040329566&single=true&output=csv"

org_type:
  dataset: "organization-types-beta"
  resource: "Organization Types (Beta) - CSV"
  format: "csv"
  headers: 2

org_type_map:
  academy: "431"
  agence un: "447"
  agence du systeme des nations unies: "447"
  autre type: "443"
  civile society: "501"
  cooperation internationale: "501"
  croix rouge: "445"
  donantes: "433"
  entite gouvernementale: "435"
  gouvernement: "435"
  gov: "435"
  govt: "435"
  ingo: "437"
  institution etatique: "435"
  international institution: "438"
  international ngos: "437"
  local ngo: "504"
  mouv cr: "445"
  mouvement croix rouge: "445"
  mouvement de la croix rouge: "445"
  movimiento de la cruz roja media luna roja: "445"
  nations unies: "447"
  naciones unidas: "447"
  nngo: "441"
  observer: "502"
  ong int: "437"
  ong internacional: "437"
  ong internationale: "437"
  ong nat: "441"
  ong national: "441"
  ong nacional: "441"
  ong nationale: "441"
  organisation des nations unies: "447"
  organismo internacional: "438"
  others: "443"
  otro: "443"
  programme de developpement: "503"
  red cross: "445"
  red cross movement: "445"
  red cross mvt: "445"
  red cross and red crescent movement: "445"
  religious group: "446"
  service etatique: "435"
  sociedad civil: "501"
  societe civile: "501"
  un: "447"
  un agency: "447"
  un agencies: "447"
